#include <iostream>
#include <stdexcept>

using namespace std;

double calculateY(int x, int n) {
    double y = 0;

    if (x <= 0) {
        for (int i = 0; i < n; i++)
            y *= i + x;
    }
    else {
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++)
                y += (x + i) / (i + j + 1);
        }
    }

    return y;
}

int inputWithValidation(const string& prompt, int minValue) {
    int value;
    cout << prompt;
    cin >> value;

    if (cin.fail() || value < minValue) {
        cin.clear();
        cin.ignore(numeric_limits<streamsize>::max(), '\n');
        throw invalid_argument("Ошибка: введено некорректное значение.");
    }

    return value;
}

void processInput() {
    int n = inputWithValidation("Введите n>=4, n=", 4);
    int x = inputWithValidation("Введите x= ", 0);

    double y = calculateY(x, n);

    cout << "x= " << x << "; y= " << y << endl;
}

int main() {
    setlocale(LC_ALL, "RUS");

    try {
        processInput();
    }
    catch (const exception& e) {
        cerr << e.what() << endl;
        return 1;
    }

    return 0;
}
